apiVersion: v1
kind: Service
metadata:
  name: backendps
spec:
  selector:
    app: backendps
  ports:
  - port: 4000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendps
  labels:
    app: backendps
spec:
  selector:
    matchLabels:
      app: backendps
  replicas: 1
  template:
    metadata:
      labels:
        app: backendps
    spec:
      containers:
      - name: backendps
        image: uk.icr.io/backendps/backendps@sha256:cf679e254c5af09a50f10f22d793259e0ea9d373975e7c223e120b563ca3dcd4
        ports:
        - containerPort: 4000
        env:
        - name: DISABLE_WEB_APP
          value: "false"