#Documentación para la API de Proyecto Backend
openapi: 3.0.0
info:
  title: Proyecto Backend
  description: Documentación para la API de Proyecto Backend
  version: 1.0.0

servers:
  - url: https://backendps.vercel.app/ 
    description: Local server

tags:
  - name: Usuario
    description: Endpoints para el manejo de la información relacionada con los usuarios

paths:

  /users/register:
    post:
      tags:
        - Usuario
      summary: Registro de usuario
      #Token?
      requestBody:
        description: Datos del usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/regUsuario'
      responses:
        '201':
          description: Usuario registrado
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /users/login:
    post:
      tags:
        - Usuario
      summary: Login de usuario
      #Token?
      requestBody:
        description: Datos del usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/logUsuario'
      responses:
        '200':
          description: Usuario logueado
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'


components:

  responses:
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Not Found
    InternalServerError:
      description: Internal Server Error
      
  
  schemas:
    regUsuario:
      type: object
      properties:
        nickname:
          type: string
          description: Nickname del usuario

        email:
          type: string
          description: Email del usuario
          format: email

        password:
          type: string
          description: Contraseña del usuario (8-16 caracteres, alfanuméricos)
          pattern: "^[A-Za-z0-9]{8,16}$"


    logUsuario:
      type: object
      properties:
        email:
          type: string
          description: Email del usuario
          format: email

        password:
          type: string
          description: Contraseña del usuario
    
