#  * Autores: Iker Morán, Jaime Berruete, Leonor Murphy
#  * Fecha: Mayo 2023
#  * Path: database\docker-compose.yml
#  * Descripción: Configuración de docker para los servicios db y app
version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
volumes:
  db:
    driver: local
